name: CI
on: push

jobs:
  Lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 20, 21]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run lint --if-present
